package rules;

// 引入实体
import com.example.droolstest02.entity.TestNoneEntity;

// 编写规则
rule "att_active_group_0"
    activation-group "group001"
    when
        TestNoneEntity(str == "activegroup001")
    then
        System.out.println("active-group001");
end

// 编写规则
rule "att_active_group_1"
    activation-group "group001"
    when
        TestNoneEntity(str == "activegroup001")
    then
        System.out.println("active-group001");
end

// 编写规则
rule "att_active_group_2"
    activation-group "group002"
    when
        TestNoneEntity(str == "activegroup001")
    then
        System.out.println("active-group002");
end

// 编写规则
rule "att_active_group_3"
    activation-group "group002"
    when
        TestNoneEntity(str == "activegroup001")
    then
        System.out.println("active-group002");
end
