package rules;

// 引入实体
import com.example.droolstest02.entity.TestNoneEntity;

// 编写规则
rule "att_agenda_group_0"
    agenda-group "group001"
    when
        TestNoneEntity(str == "agendagroup")
    then
        System.out.println("att_agenda_group_0");
end

// 编写规则
rule "att_agenda_group_1"
    agenda-group "group001"
    when
        TestNoneEntity(str == "agendagroup")
    then
        System.out.println("att_agenda_group_1");
end

// 编写规则
rule "att_agenda_group_2"
    agenda-group "group001"
    when
        TestNoneEntity(str != "agendagroup")
    then
        System.out.println("att_agenda_group_2");
end

// 编写规则
rule "att_agenda_group_3"
    agenda-group "group001"
    when
        TestNoneEntity(str != "agendagroup")
    then
        System.out.println("att_agenda_group_3");
end
