package rules;

// 引入实体
import com.example.droolstest02.entity.EnableEntity;


// 编写规则
rule "att_enabled_0"
    enabled true
    when
        EnableEntity(name == "诸葛十三")
    then
        System.out.println("enabled=true");
end

// 编写规则
rule "att_enabled_1"
    enabled false
    when
        EnableEntity(name == "诸葛十三")
    then
        System.out.println("enabled=false");
end

// 编写规则
rule "att_enabled_2"
    when
        EnableEntity(name == "诸葛十三")
    then
        System.out.println("enabled=default");
end