package rules;

// 引入实体
import com.example.droolstest02.entity.TestQueryEntity;
global java.lang.Integer count
global java.util.List data

query "query_1"
    $test:TestQueryEntity(name == "张三")
end

query "query_2"(String qName, Integer qAge)
    $test:TestQueryEntity(name == qName && age == qAge)
end

rule "query_rule_0"
    when
        $test:TestQueryEntity(name == "诸葛十三")
        or query_1()
        or query_2("李四", 18;)
    then
        System.out.println("使用自定义query查询结果");
end

