package rules;

// 引入实体
import com.example.droolstest02.entity.TestNoneEntity;



rule "rhsplus_modify01"
    when
        $test01:TestNoneEntity(i == 18)
    then
        System.out.println("18啦，可以谈恋爱啦!");
        System.out.println("过了3年，21了");
        modify($test01){
            setI(21)
        }
end

rule "rhsplus_modify02"
    when
        $test01:TestNoneEntity(i == 21)
    then
        System.out.println("21啦，赶紧找对象!");
        System.out.println("过了9年，30了");
        modify($test01){
            setI(30)
        }
end

rule "rhsplus_modify03"
    when
        $test01:TestNoneEntity(i == 30)
    then
        System.out.println("30啦，还没对象！");
end
