package rules;

// 引入实体
import com.example.droolstest02.entity.TestNoneEntity;



rule "rhsplus_update01"
    when
        $test01:TestNoneEntity(i == 18)
    then
        System.out.println("18啦，可以谈恋爱啦!");
        System.out.println("过了3年，21了");
        $test01.setI(21);
        update($test01);
end

rule "rhsplus_update02"
    when
        $test01:TestNoneEntity(i == 21)
    then
        System.out.println("21啦，赶紧找对象!");
        System.out.println("过了9年，30了");
        $test01.setI(30);
        update($test01);
end

rule "rhsplus_update03"
    when
        $test01:TestNoneEntity(i == 30)
    then
        System.out.println("30啦，还没对象！");
end
