package rules;

// 引入实体
import com.example.droolstest02.entity.TestNoneEntity
import java.util.Date
import java.time.LocalDateTime
import java.time.ZoneOffset;

// 编写规则
rule "att_timer_0"
    timer(10s 5s)
    when
        TestNoneEntity(str == "timer")
    then
        System.out.println("att_timer_0："+ LocalDateTime.now().toEpochSecond(ZoneOffset.UTC));
end

// 编写规则
rule "att_timer_2"
    // 10秒执行一次
    timer(cron:0/10 * * * * ?)
    when
        TestNoneEntity(str == "timer")
    then
        System.out.println("att_timer_2："+ LocalDateTime.now().toEpochSecond(ZoneOffset.UTC));
end
