package rules;

// 引入实体
import com.example.droolstest.entity.Order;
import com.example.droolstest.entity.User;

// 编写规则
rule "add0"
    no-loop true
    lock-on-active true
    salience 1
    when
        $order : Order(price <= 100)
    then
        $order.setScore(0);
        update($order)
end

rule "add100"
    no-loop true
    lock-on-active true
    salience 1
    when
        $order : Order(price > 100 && price <= 500)
    then
        $order.setScore(100);
        update($order)
end

rule "add500"
    no-loop true
    lock-on-active true
    salience 1
    when
        $order : Order(price > 500 && price <= 1000)
    then
        $order.setScore(500);
        update($order)
end

rule "add1000"
    no-loop true
    lock-on-active true
    salience 1
    when
        $order : Order(price > 1000)
    then
        $order.setScore(1000);
        update($order)
end